# Site settings
description: A place to talk about what I am learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mwwolters.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: test
user_description: An IT Security Professional
user_title: IT Security Professional
email: mwwolters@gmail.com
twitter_username: mwwolters
github_username:  mwwolters
gplus_username:  mwwolters
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
